### ISSUE TITLE
Use kafka 3.3.1 client

### ISSUE THREAD

**Issue by tooptoop4** [SolaceProducts/pubsubplus-connector-kafka-source#49]
https://github.com/SolaceProducts/pubsubplus-connector-kafka-source/pull/52

**Comment by bczoma** [comment]
@tooptoop4 , noted.

**Comment by mackenza** [comment]
Hello @tooptoop4 . I am the product manager for this connector. We are looking into creating a new release to pick up the new Kafka client version, but I don't have a timeframe for this at the moment. 
Is this issue logged to keep current or because the release doesn't work anymore?

Regards,
Andrew

**Comment by tooptoop4** [comment]
the release still works but the newer version will enable new functionality

**Comment by Nephery** [comment]
Done with #66
